### PR TITLE
Upgrade to Rails 5.1.4

### PR DESCRIPTION
**Pull request by jwworth**

### CODE REVIEW

**Comment by greysteil** [comment]
@jwworth - would you be up for automatically generating dependency update PRs like this one? It can't fix deprecated methods (yet..) but the tool I built at my last job, [Dependabot](https://dependabot.com), will create a PR for you every time a new version comes out. It's totally free for open source - I'm just trying to get more people using it so the [compatibility scores](https://dependabot.com/compatibility-score.html) are as accurate as possible.

**Comment by jwworth** [comment]
@greysteil Thanks for posting. It's an interesting idea. The deprecations are big part of upgrading, but a pull request that changes the Gemfile might start the ball rolling and keep me informed.

I tried installing Dependabot, but stopped when I was asked if I would grant Dependabot 'Write access to code'. I'm unclear what that means, and it seems like potentially a lot of power to give an automated tool.

**Comment by greysteil** [comment]
@jwworth - ack, yeah, it's a bit of a rock and a hard place on that one. It asks for write access so it can create the PR branches on your repo (so that CI runs as normal, etc.). That's the natural flow for private repos, but for public ones it feels a bit odd - you wouldn't expect a contributor like a bot to need write access.

We did put a guarantee that Dependabot will *never* make updates to your master or default branch in its terms of service (it only ever pushes to branches namespaced with `dependabot`), but I appreciate it's still a scary permission to give!

**Comment by jwworth** [comment]
@greysteil thanks for explaining that. I figured it was standard Github permissions language, which can make permissions sound more ominous than they are (which is a good thing from a user's perspective). This project is a sandbox for my Rails development ideas and skills, so I'm going to keep managing my own updatess. I appreciate the idea and wish you luck.

**Pull request closed without merging**
